//public class ExceptionHandling {
//    public static void main(String[] args) {
//        //1---------------------------------------------------------
//        try {
//            int a = 30 / 0;
//        } catch (ArithmeticException e) {
//            System.out.println("Exception occur");
//        } catch (ArithmeticException e) {
//            System.out.println("Exception occur");
//        }
//        //2------------------------------------------------
//        try {
//            int a = 30 / 0;
//        } catch (ArithmeticException e) {
//            System.out.println("Exception occur");
//        }
//        System.out.println("HELLO");
//        catch(Exception e){
//            System.out.println("Exception occur");
//        }
//        //3-------------------------------------------------
//        try {
//            int a = 30 / 0;
//        }
//        finally
//            {
//                System.out.println("Exception occur");
//            }
//            catch(ArithmeticException e){
//                System.out.println("Exception occur");
//            }
//        //4--------------------------------------------------
//
//        try {
//            int a = 30 / 0;
//        }catch (ArithmeticException e){
//            System.out.println("Exception occur");
//        }catch (ArithmeticException e){
//            System.out.println("Exception occur");
//        }
//
//    }
//}
